### ISSUE TITLE
Publishing on gh-pages branch

### ISSUE THREAD

**Issue by asewnath** [JCSDA-internal/eva-docs#2]
Could someone with write access to this repository publish the eva-docs website using the gh-pages branch. To do this, go to Setting > Pages > and select "Deploy from a branch" as source with gh-pages selected for the branch.

**Comment by danholdaway** [comment]
It's built now https://jcsda-internal.github.io/eva-docs/

@climbfuji would it be possible to give @asewnath access to the pages part of the settings?
