### ISSUE TITLE
Please follow branch naming conventions for eva / eva-docs

### ISSUE THREAD

**Issue by climbfuji** [JCSDA-internal/eva-docs#20]
## Description

At JCSDA, we use the following branch naming conventions:
- `develop`
- `main` (were applicable, we are trying to move away from this and only use `develop`)
- `release/*` for releases
- `feature/*` for feature branches
- `bugfix/*` for bug fixes, acceptable is also `hotfix/*`

Please do not use other branch names, for example `myusername-patch2`. Thanks!

## Requirements

See above.

## Acceptance Criteria (Definition of Done)

See above.

## Dependencies

None.

**Comment by asewnath** [comment]
Sorry about that, will delete all the patch branches.

**Comment by climbfuji** [comment]
Thanks!
